- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - networkmanager
    - nm-connection-editor
    - network-manager-applet
  become: true   

- name: Start service
  ansible.builtin.systemd_service:
    service: NetworkManager.service
    state: started
    enabled: true
  become: true   
