- name: Install rust
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/rust_install \
    && sh /tmp/rust_install -y


- name: Install rust-analyzer
  ansible.builtin.shell: |
    ~/.cargo/bin/rustup component add rust-analyzer
