- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install grub
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - grub
    - os-prober
  become: true
 
- name: Set grub defaults
  ansible.builtin.copy:
    src: files/etc_default_grub
    dest: /etc/default/grub
    backup: yes
  become: true
  
- name: Set background image
  ansible.builtin.copy:
    src: files/grub.png
    dest: /boot/grub/grub.png
  become: true

- name: Set iso boot
  ansible.builtin.copy:
    src: files/etc_grub_d_40_custom 
    dest: /etc/grub.d/40_custom
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Make config
  ansible.builtin.shell: grub-mkconfig -o /boot/grub/grub.cfg
  become: true
