- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install cron
  community.general.pacman:
    name: "{{item}}"
    state: latest
  become: true   
  loop:
    - cronie
    
- name: Start service
  ansible.builtin.systemd_service:
    service: cronie.service
    state: started
    enabled: true
  become: true
