- name: OpenSSH
  hosts: localhost

  tasks:

  - name: Install openssh
    community.general.pacman:
      name: openssh
      update_cache: true
      state: present
    become: true   

  - name: Start service
    ansible.builtin.systemd_service:
      service: sshd.service
      state: started
      enabled: true
    become: true   
