- name: OpenSSH
  hosts: localhost

  tasks:

  - name: Install openssh
    community.general.pacman:
      name: openssh
      update_cache: true
      state: present
    become: true   

  - name: Enable X11
    ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: ^#(X11.*)
      replace: \1
      # backrefs: yes
  # - name: Enable X11
  #   ansible.builtin.shell: |
  #     sed -i -e 's/#X11/X11/' /etc/ssh/sshd_config
    become: true

  - name: Start service
    ansible.builtin.systemd_service:
      service: sshd.service
      state: started
      enabled: true
    become: true   
