- name: OpenSSH
  hosts: localhost
  become: true

  tasks:

  - name: Install openssh
    community.general.pacman:
      name: openssh
      update_cache: true
      state: present
    become: true   

  - name: Enable X11
    ansible:builtin:shell: |
      sed -i -e 's/#X11/X11/' /etc/sshd/sshd_config
    become: true   

  - name: Start service
    ansible.builtin.systemd_service:
      service: sshd.service
      state: started
      enabled: true
    become: true   
