- name: OpenSSH
  hosts: localhost
  vars_files:
    - vars.yml  

  tasks:

  - name: vars
    # ansible.builtin.include_vars: 
    #   file: vars.yml
    ansible.builtin.debug:
      msg: "{{xxx}}"

    
  - name: Install openssh
    community.general.pacman:
      name: openssh
      update_cache: true
      state: present
    become: true   

  - name: Enable X11
    ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: ^#(X11.*)
      replace: \1
    become: true

  - name: Start service
    ansible.builtin.systemd_service:
      service: sshd.service
      state: started
      enabled: true
    become: true   
