- ansible.builtin.include_role:
    name: "{{item}}"
  loop:
    - cron

- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install grub
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - rclone
  become: true
 
- name: Mount backup drive
  ansible.posix.mount:
    path: /var/store  
    src: LABEL=STORE
    fstype: ext4
    opts: defaults
    state: mounted
  become: true   

- name: Set cron file
  ansible.builtin.copy:
    src: files/
    dest: /etc/cron.daily/
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become: true
