- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - xorg
    - xclip
    - xorg-xinit
    - xorg-xrandr
    - arandr
    - autorandr
    - firefox
    - x11vnc
    - xss-lock
  become: true   

- name: Install AUR
  yay: 
    name: "{{item}}" 
    state: latest
  loop:
    - xlayoutdisplay
    
- name: Set background image
  ansible.builtin.copy:
    src: files/
    dest: /etc/X11/xorg.conf.d
  become: true

   
