- name: Install ntp
  community.general.pacman:
    name: ntp
    update_cache: true
    state: latest
  become: true

- name: Start service
  ansible.builtin.systemd_service:
    service: ntpd.service
    state: started
    enabled: true
  become: true
