- name: update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Mount virtual drive
  ansible.posix.mount:
    path: /var/virtual
    src: LABEL=Virtual
    fstype: ext4
    opts: defaults
    state: mounted
  become: true   

- name: Create the ISO dir
  ansible.builtin.file:
    path: /var/virtual/ISO
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true   

- name: Mount ISO drive
  ansible.posix.mount:
    path: /var/virtual/ISO
    src: LABEL=ISO
    fstype: ext4
    opts: defaults
    state: mounted
  become: true   

- name: Install packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - archiso
  become: true   

   
