###########################
## Main system playbook.
## This and any child playbooks should be run on the local host.
###########################

- hosts: localhost
  roles:
  - packages
  - sshd
  - grub
# grub configuration
 # format and background image
 # include iso booting 
# stow
# nvim 
# tmux 
    #npt 
    #snapper 
    #sddm 
    #timeshift 
    #plymouth
  
