- name: update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - bluez
    - bluez-utils
  become: true   

- name: Start service
  ansible.builtin.systemd_service:
    service: bluetooth.service
    state: started
    enabled: true
  become: true   
