- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - sway
    - swayidle
    - swaylock 
    - swaybg 
    - wlroots
    - polkit 
    - wob
    - wayvnc
    - wofi
    - waybar
    - wallutils
  become: true   

- name: Install AUR
  yay: 
    name: "{{item}}" 
    state: latest
  loop:
    - clipman
    - swaynagmode 
    #TODO: - swayrandr 
    - wdisplays
