- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - i3-wm
    - rofi
    - i3lock
    - kitty
    - picom
    - polybar
    - feh
    - i3status
    - rofimoji
  become: true   

- name: Install AUR
  yay: 
    name: "{{item}}" 
    state: latest
  loop:
    - i3-battery-popup
    - autotiling
