#!/bin/bash                                                                                                         

DIR=/tmp/backup-$(date +%s)
mkdir -p ${DIR}
mount /dev/disk/by-label/BACKUP ${DIR}
${DIR}/bin/backup.sh
umount -R ${DIR}
rmdir ${DIR}

