 - name: Update cache
   community.general.pacman:
     update_cache: true
   become: true   

 - name: Install fonts
   community.general.pacman:
     name: "{{item}}"
     state: latest
   loop:
     - ttf-noto-nerd
     - ttf-0xproto-nerd
     - otf-monaspace-nerd
     - ttf-dejavu-nerd
     - ttf-jetbrains-mono-nerd
     - ttf-terminus-nerd
     - ttf-font-awesome
     - ttf-meslo-nerd
     - noto-fonts-emoji
     - ttf-inconsolata-nerd
   become: true   

 - name: Install AUR
   yay: 
    name: "{{item}}" 
    state: latest
   loop:
     - ttf-font-icons
     - ttf-ionicons

