- name: update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install pacman packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  loop:
    - less
    - inetutils
    - mercurial
    - neovim
    - bat
    - yazi
    - which
    - tree
    - base-devel
    - fzf
    - python3
    - python-pip
    - python-pynvim
    - rsync
    - stow
    - tmux
    - neofetch
    - starship
    - w3m
    - unzip
    - lua51
    - lua51-jsregexp
    - luarocks
    - wget
    - ripgrep
    - nodejs
    - npm
    - ruby
    - tree-sitter-cli
    - fd
    - cpanminus
    - composer
    - go
    - jdk-openjdk
    - julia
    - net-tools
    - qemu-ui-curses
    - htop
    - qmk
  become: true   

- name: Instal npm packages
  community.general.npm:
    name: "{{item}}"
    global: true
  loop:
    - neovim
  become: true   

- name: Install rust for cargo 
  ansible.builtin.include_role:
    name: rust

- name: Install cargo packages 
  community.general.cargo:
    name: "{{item}}"
    executable: ~/.cargo/bin/cargo
  loop:
    - stylua

- name: Install gem packages
  community.general.gem:
    name: "{{item}}"
    user_install: false
  loop:
    - neovim
  become: true   

- name: Install perl packages
  community.general.cpanm:
    executable: /usr/bin/vendor_perl/cpanm
    name: "{{item}}"
  loop:
    - Neovim::Ext
  become: true   

- name: Clone yay
  ansible.builtin.git:
   repo: https://aur.archlinux.org/yay.git 
   dest: /tmp/yay

- name: Install yay 
  ansible.builtin.shell: |
    cd /tmp/yay && yes | makepkg -si

- name: Install AUR packages
  yay: 
    name: "{{item}}" 
    state: latest
  loop:
    - bashmount
    - lemonade-git
    
