- name: update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install pacman packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  become: true   
  loop: "{{pacman}}"

- name: Instal npm packages
  community.general.npm:
    name: "{{item}}"
    global: true
  loop:
    - neovim
  become: true   

- name: Install rust for cargo 
  ansible.builtin.include_role:
    name: rust

- name: Install cargo packages 
  community.general.cargo:
    name: "{{item}}"
    executable: ~/.cargo/bin/cargo
  loop:
    - stylua

- name: Install gem packages
  community.general.gem:
    name: "{{item}}"
    user_install: false
  loop:
    - neovim
  become: true   

- name: Install perl packages
  community.general.cpanm:
    executable: /usr/bin/vendor_perl/cpanm
    name: "{{item}}"
  loop:
    - Neovim::Ext
  become: true   

- name: Clone yay
  ansible.builtin.git:
   repo: https://aur.archlinux.org/yay.git 
   dest: /tmp/yay

- name: Install yay 
  ansible.builtin.shell: |
    cd /tmp/yay && yes | makepkg -si

- name: Install AUR packages
  yay: 
    name: "{{item}}" 
    state: latest
  loop: "{{aur}}"
    
