- ansible.builtin.include_role:
    name: "{{item}}"
  loop:
    - packages-core

- name: Update cache
  community.general.pacman:
    update_cache: true
  become: true   

- name: Install pacman packages
  community.general.pacman:
    name: "{{item}}"
    state: latest
  become: true   
  loop: "{{pacman}}"

- name: Install AUR packages
  yay: 
    name: "{{item}}" 
    state: latest
  loop: "{{aur}}"

