- name: Install snapper
  community.general.pacman:
    name: "{{item}}"
    update_cache: true
    state: latest
  loop:
    - boost-libs
    - snapper 
    - inotify-tools 
  become: true

- name: Install snapper tools
  yay: 
    name: "{{item}}" 
    state: latest
  loop:
    - btrfs-assistant
    - snap-pac
     
- name: Create configs
  ansible.builtin.shell:
    snapper -c root create-config / \
    && snapper -c home create-config /home
  become: true


- name: Copy configs
  ansible.builtin.copy:
    src: files/ 
    dest: /etc/snapper/configs/
  become: true 

- name: Start services
  ansible.builtin.systemd_service:
    service: "{{item}}"
    state: started
    enabled: true
  loop:
    - snapper-timeline.timer
    - snapper-cleanup.timer
  become: true

